### ISSUE TITLE
I can't run 8192 in my local

### ISSUE THREAD

**Issue by e274426380** [EthosWallet/Sui8192#6]
Env: Windows10
use: yarn && yarn build && npx browser-sync start --server
```
Error: Can't walk dependency graph: Cannot find module 'C:\Users\zhou\Desktop\Sui\code\Sui8192\js\*' from 'C:\Users\zhou\Desktop\Sui\code\Sui8192\js\_fake.js'
    required by C:\Users\zhou\Desktop\Sui\code\Sui8192\js\_fake.js
    at C:\Users\zhou\Desktop\Sui\code\Sui8192\node_modules\resolve\lib\async.js:167:35
    at load (C:\Users\zhou\Desktop\Sui\code\Sui8192\node_modules\resolve\lib\async.js:186:43)
    at onex (C:\Users\zhou\Desktop\Sui\code\Sui8192\node_modules\resolve\lib\async.js:211:17)
    at C:\Users\zhou\Desktop\Sui\code\Sui8192\node_modules\resolve\lib\async.js:24:69
    at FSReqCallback.oncomplete (node:fs:198:21)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by e274426380** [comment]
@jaredcosulich sure, I pulled once today
